apiVersion: apps/v1
kind: Deployment
metadata:
  name: molovol
spec:
  replicas: 2
  selector:
    matchLabels:
      app: molovol
  template:
    metadata:
      labels:
        app: molovol
    spec:
      containers:
      - name: molovol-container
        image: bsvogler/molovol:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: "userupload"
          name: userupload
      volumes:
      - name: userupload
        persistentVolumeClaim:
          claimName: io
---
apiVersion: v1
kind: Service
metadata:
  name: molovol-service
spec:
  selector:
    app: molovol
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: molovol-ingress
spec:
  rules:
  - host: app.molovol.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: molovol-service
            port:
              number: 5000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: io
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path